### ISSUE TITLE
The height of hero section and other changes

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/pro1-chemcon#13]
fix the height such that lower portion should be visible.

add organized by in seperate lines

Institute of chemical engineers
Doba next line
NITj next line

below that logos and other content what ever you have given

**Comment by AvnashKumar** [comment]
done

**Comment by harimurugan1989** [comment]
Height is not fixed for all screens. still contents like about and news are visible.

![image](https://github.com/xceed-nitj/pro1-chemcon/assets/88608850/2251fa7c-b405-4129-88fd-a337a47e306b)
 
Change NITJ to "NIT Jalandhar"

**Comment by AvnashKumar** [comment]
check it now sir
